'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MpressGUI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''                   MATCODE Compressor
        '''                  
        '''         Reporting Problems and Receiving Support
        '''         
        '''
        '''  At first make sure that the problem you have encountered while packing
        '''or executing compressed application is not an ordinary situation or a known
        '''problem: see MPRESS ReadMe, TechInfo. Only if the problem is not known, send
        '''an email to ve@matcode.com, otherwise there&apos;s no need to produce extra
        '''traffic, it does not stimulate developers in any way.
        '''In your email specify the condi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BugReport() As String
            Get
                Return ResourceManager.GetString("BugReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to          
        '''
        '''[1]  Which compression algorithm uses MPRESS?
        '''[2]  What advantages of this compression?
        '''[3]  Whether I need to buy some license in order to use MPRESS?
        '''[4]  &quot;In-place decompression&quot; - How does it work?
        '''[5]  Why MPRESS does not have decompression option?
        '''[6]  Can MPRESS protect my program against crackers?
        '''[7]  Do compressed files load faster or slower?
        '''[8]  What should I use instead of Assembly.Location?
        '''[9]  What should I use instead of Module.FullyQualifiedName?
        '''
        '''
        '''
        '''[1]  Which comp [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FAQ() As String
            Get
                Return ResourceManager.GetString("FAQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to           MATCODE COMPRESSOR  GUI
        '''
        '''[1] Import or drop the file
        '''[2] Browse where you want to save your data
        '''[3] Compress
        '''
        '''This version supports:
        '''	AMD64/PE32+/EXE - x64 (AMD64) Executables
        '''	AMD64/PE32+/DLL - x64 (AMD64) Libraries
        '''	x86/PE32/EXE    - x86 Executables
        '''	x86/PE32/DLL    - x86 Libraries
        '''	anyCPU/.NET/EXE - any CPU .NET (except. CF) Applications
        '''	x86/.NET/EXE    - x86 .NET Applications
        '''	AMD64/.NET/EXE  - AMD64 .NET Applications
        '''	IA64/.NET/EXE   - IA64 .NET Applications
        '''	x86/MACH-O/APP   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Help() As String
            Get
                Return ResourceManager.GetString("Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''v2.19
        ''' - bugfix: support x64 on Windows 8
        '''
        '''
        '''v2.18
        ''' - support for .NET Framework v4.0
        ''' - support for .NET x64
        ''' - bugfix: possible deadlock on the overloaded computer
        '''
        '''v2.17
        ''' - new option -r to not compress resources
        ''' - bugfix: in processing of relocations
        '''
        '''v2.15
        ''' - bugfix: compressed TYPELIB and REGISTRY resources of ActiveX components
        ''' - bugfix: crash on empty import directory entry
        '''
        '''v2.12
        ''' - bugfix: crash when Open GL with some ATI adapters
        ''' - added compression filter for 32-bit and 64 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property History() As String
            Get
                Return ResourceManager.GetString("History", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''MPRESS	Matcode comPRESSor
        '''Copyright (c) 2007-2009, Vitaly Evseenko, MATCODE Software
        '''All rights reserved.
        '''
        '''This program is free for commercial and non-commercial use as long as
        '''the following conditions are aheared to.
        '''
        '''Copyright remains Vitaly Evseenko (MATCODE Software), and as such any
        '''Copyright notices in the code are not to be removed.
        '''
        '''Redistribution and use, without modification, is permitted and reproduce
        '''the above copyright notice  and the following disclaimer in the
        '''documentation and/ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property license() As String
            Get
                Return ResourceManager.GetString("license", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property mpress() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("mpress", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
